name: Deploy to Firebase Hosting on Master
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify public directory
        run: |
          if [ ! -d "public" ]; then
            echo "Error: public directory not found"
            exit 1
          fi

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BADI_COUNTS_ZH }}
          projectId: badi-counts-zh
          channelId: live
